### ISSUE TITLE
Where am I expected to find the required values?

### ISSUE THREAD

**Issue by GingkoFr** [akshettrj/watgbridge#33]
Hello.

I've just tried to build your application.
It seems to compile fine on Linux Debian 12 _(with just a deprecation warning)_.
But in your installation instructions, you wrote :

`Copy sample_config.yaml to config.yaml and fill the values, there are comments to help you.`

In the config.yaml file, I have :

```
telegram:
  bot_token: 186779
  #api_url: http://localhost:8082 # Uncomment if you have a local bot API server running (for bypassing file size limits)
  self_hosted_api: false
  owner_id: 704338780
  sudo_users_id:
    - 704338780
  target_chat_id: -100423424      # This is the chat where messages will be forwarded
  skip_video_stickers: false      # Setting this as true will stop trying to convert telegram video stickers to webp and sending them
  skip_setting_commands: false    # This will not show you list of commands when you start typing / in telegram

```
… with several numeric values which certainly don't belong to me.

**Where am I expected to find the values to put instead?**
There are no comments to help me about that.
The only one that I may have found is the bot_token, but still, it doesn't looks like a 6 digits value.

And I suppose that the WhatsApp part may have values that I will have to find, too.

Gingko.
